# Generated by Django 4.1.4 on 2022-12-22 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_project_image_project_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='body',
        ),
    ]
