# Generated by Django 4.1.4 on 2022-12-24 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload',
            new_name='CV',
        ),
    ]
